### ISSUE TITLE
可以把说说也一块爬下来吗?

### ISSUE THREAD

**Issue by ustcjerry** [frostming/renren-dumps#1]
rt

**Comment by frostming** [comment]
Sure

**Comment by ustcjerry** [comment]
额，你在爬你自己账户的内容，而且保存下来的编码不对。。。

**Comment by frostming** [comment]
@ustcjerry 能详细一点吗？你想要什么？得到的结果是什么？

**Comment by ustcjerry** [comment]
1、在这行里
https://github.com/frostming/renren-dumps/blob/c2d47b8ed858b13c25b4eccddf2ee05488abe0d3/spider.py#L179
id 是写死的
2、本地运行会报错
Traceback (most recent call last):
  File "spider.py", line 241, in <module>
    spider.main()
  File "spider.py", line 208, in main
    self.dump_status()
  File "spider.py", line 202, in dump_status
    f.write(f"### {heading}\n\n{content}\n\n")
UnicodeEncodeError: 'gbk' codec can't encode character '\u2665' in position 210: illegal multibyte sequence

**Comment by ustcjerry** [comment]
可以了  赞！
