### ISSUE TITLE
可以把 说说, 日志, 照片 下的每条评论和点赞数也爬下来吗

### ISSUE THREAD

**Issue by ustcjerry** [frostming/renren-dumps#4]
rt

**Comment by frostming** [comment]
此项目最初目的是想把相册（文章）备份下来好转移到另个地方。所以目前不在scope内。

推荐Github上另一个优秀的全备份+可视化工具 https://github.com/whusnoopy/renrenBackup，不过他这个没有开多线程，爬起来比较慢

**Comment by ustcjerry** [comment]
ok, thx~~
