### ISSUE TITLE
关于renren-dumps程序的反馈 ，有些问题请教，打扰了

### ISSUE THREAD

**Issue by niujie005** [frostming/renren-dumps#6]
您好，不知道该怎么称呼您，冒昧的发邮件给您，我从网上搜索到您编程的人人网备份工具，使用后成功的下载备份了所有的图片，可是状态和日志都备份失败，没有任何数据，可能是人人网的网页版现在无法打开日志的原因，我还得知使用3g.renren.com这个链接还可以查看完整的日志，不知道您是否有办法抓取这个网址的日志数据。
人人网上的日志和状态是我们永远难忘的青春，特别感谢您制作的备份程序，不知道您是否有时间修改这个程序，就算您没有时间和精力修改，我还是要感谢您的工具帮我备份了所有的图片，在不远的将来，也许人人网就彻底消失了，您的工具功德无量，再次感谢，盼复。

**Comment by frostming** [comment]
看到你邮件我去人人看了下，发现日志页面真的没有了，看来备份已迫在眉睫，以后只会有更多的东西找不回来。我会去尝试3g页面，感谢提醒。发自我的华为手机

**Comment by frostming** [comment]
@niujie005 日志已经恢复下载，发布了1.1版本https://github.com/frostming/renren-dumps/releases ，加了credit，请享用

**Comment by niujie005** [comment]
我下载最新版试了，好像还是不行，日志的文件夹是空的，图片可以，是我哪里操作有问题吗？
求助




在 2019-10-26 21:09:34，"Frost Ming" <notifications@github.com> 写道：


Closed #6.

**Comment by frostming** [comment]
@niujie005 图片下载没有改动，原来能下新版就能下

**Comment by niujie005** [comment]
图片一直都没问题，新版旧版都能下，但是日志我用了新版本也不能下载，要不我把 账号和密码给您，您帮我导出一下？太麻烦您了





在 2019-10-28 09:09:28，"Frost Ming" <notifications@github.com> 写道：


@niujie005 图片下载没有改动，原来能下新版就能下

**Comment by frostming** [comment]
![image](https://user-images.githubusercontent.com/16336606/67652868-e33c7b80-f981-11e9-8f8c-7835fa3278c6.png)
这个不是你吗？.session删过了吗
